### PR TITLE
Allow 64bit migration versions

### LINKED ISSUE #83: The refinery_schema_history version colum is too small for time based versions.
Hi,

It's pretty common to use time based version numbers for migration files (e.g. migrations of Active Record or Diesel). The current implementation of refinery is only using the column type INT4 for the version column, which is too small to hold the current time based on a YEAR-MONTH-DAY-HOUR-MINUTE basis.

Is there any special reason not to use INT8 for the version column? The rust code seems to use a i32, so a switch to i64 should be possible.

(I'm using a postgres database).

### PR DESCRIPTION
**Pull request by ankhers**
This should allow the versions to be parsed and inserted into the database.

I still need to add a command to the CLI to generate a migration for each supported database.

fixes #83

### CODE REVIEW

**Comment by ankhers** [comment]
I'm not really sure what the best command name to generate the migration. I'm open to suggestions if anyone has any.

**Comment by jxs** [comment]
Hi, and thanks for starting this. I would suggest `update-schema`?

**Comment by ankhers** [comment]
So, I have been thinking about the auto generated migration and I am wondering whether this is something we want to do. Some people will prefer to have their migrations written in rust, others will prefer sql. Even then, there is the difference between versioned and unversioned migrations. Should we just have the ability to generate all of these different types of migrations, or should there just be a note in the changelog and readme stating to migrate the table?

**Comment by ankhers** [comment]
Or maybe instead of creating a migration, we could just have refinery take care of it? Similar to how refinery will automatically create the schema table for you.

**Comment by jxs** [comment]
>Or maybe instead of creating a migration, we could just have refinery take care of it? Similar to how refinery will automatically create the schema table for you.

can that be done with sql standard? If so yeah definitely, thanks!

**Comment by jxs** [comment]
sorry, did not understand the question. How does this affect older migrations?

**Comment by ankhers** [comment]
Really sorry about this. I don't really understand how I managed it, but I meant to reply to the most recent comment on #83. Let me repost question there just so that everything is clear.

**Comment by taqtiqa-mark** [comment]
ON 32 bit systems this should fallback to characters, or should these longer 'version' number schemes just be character/String consistently.

I also wonder if we wouldn't have less headaches on smaller platforms if we just used `usize` and fall back to char/String when the versions number is 'too-big' for the system refinery is running on?

**Comment by lf-** [comment]
> ON 32 bit systems this should fallback to characters, or should these longer 'version' number schemes just be character/String consistently.

Bitness should not matter as long as the database supports `INT8`, which seems like a reasonable baseline requirement to be usable as a database anyway.

**Comment by lf-** [comment]
Actually, since Refinery checksums are 64 bits, it *already* requires that the DB can store a 64 bit integer.

**Comment by jxs** [comment]
Hi @mbrgm this PR was stale for more than a year before being closed, so I don't know what was missing and how would this PR be compatible with the current codebase but feel free to fork the branch and work on the feature, if you want any guidance ping me.
Cheers :)

**Pull request closed without merging**
