### PR TITLE
chore: Updated deps on all crates

### PR DESCRIPTION
**Pull request by OtaK**
Hi!

I updated the dependencies on all the crates to make sure everything is compatible with latest versions of everything.

This started as just updating for rusqlite 0.29 but I kinda got carried away 🙃

### CODE REVIEW

**Comment by krojew** [comment]
Any chance of getting this merged?

**Comment by krojew** [comment]
@jxs can you take a look? At the moment, it's not possible to use `refinery` if the version of its dependencies doesn't match what is used is by other crates/applications - it's not possible to implement `AsyncMigrate`/`Migrate` for newer versions, since it's not possible to create applied migrations due to `Migration::applied` being private.

**Review by jxs — APPROVED** [review]
Hi, and thanks for this!

**Comment by krojew** [comment]
Can someone merge? :)

**Comment by jxs** [comment]
I'll also create a release tomorrow

**Comment by jxs** [comment]
released [`0.8.8`](https://github.com/rust-db/refinery/pull/272) cheers folks :)

**Pull request merged**
