### PR TITLE
Fix default name of config file in readme

### PR DESCRIPTION
**Pull request by spebern**

### CODE REVIEW

**Comment by jxs** [comment]
Hi, thanks but the correct name is [refinery.toml](https://github.com/rust-db/refinery/blob/6d9d7423c3d18de6196e4b3fe44e344433bcdad0/refinery_cli/src/setup.rs#L27)

**Comment by spebern** [comment]
Thanks for the quick comment! I just installed the cli via `cargo install refinery_cli`.
`refinery --version` gives `refinery 0.2.0` which seems to require `Refinery.toml`.

**Comment by jxs** [comment]
yeah, this was after, though I just noticed that [there's still a line to update](https://github.com/rust-db/refinery/blob/6d9d7423c3d18de6196e4b3fe44e344433bcdad0/refinery_cli/src/setup.rs#L11) want to update your PR with that change?

**Comment by spebern** [comment]
I did. Thanks! I should have looked a little closer at source and changes. Everything just worked after I wrote it with capital letters locally and I thought it might be similar to `Cargo.toml` starting with a capital letter.
Thanks a lot for the rust-db tools!

**Comment by jxs** [comment]
thanks!

**Pull request merged**
