### PR TITLE
Bump mysql version

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Looks like there is a couple unused imports that can be removed: https://travis-ci.org/github/rust-db/refinery/jobs/689192448#L420

**Comment by jxs** [comment]
> Looks like there is a couple unused imports that can be removed: https://travis-ci.org/github/rust-db/refinery/jobs/689192448#L420

it's because the travis test only tests the lib tests with no features activated.
Btw circle ci tests seem odd, can you force push to trigger them again?
thanks

**Comment by SomeoneToIgnore** [comment]
I have no access to Circle CI logs hence no idea what went wrong. Might it be that the forked projects are not working properly with the current CI set up?

I'll push something into the branch.

**Comment by SomeoneToIgnore** [comment]
I've pushed a small typo fix, yet that seems not to change anything.

Can that be the reason:
https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories
?

**Comment by jxs** [comment]
> I've pushed a small typo fix, yet that seems not to change anything.
> 
> Can that be the reason:
> https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories
> 
> > By default, CircleCI does not build PRs from forked repositories. To change this setting, go to the Advanced Settings of your project and set the Build forked pull requests option to On.
> 
> ?
I have that activated since the beginning, and also checked this: https://support.circleci.com/hc/en-us/articles/360004346254-Workflow-status-checks-never-completes-because-of-ci-circleci-Waiting-for-status-to-be-reported, but didn't change the behavior.
PR's were working up until a couple days ago, so i suspect it's a bug with CircleCi, I have since submitted a ticket

**Comment by SomeoneToIgnore** [comment]
Ah, bummer.

In case you want to release a new version soon, go ahead and apply the changes yourself in a new pr, I'm totally fine.

**Comment by jxs** [comment]
Hi, so it really was a bug on their side, i have just received a response from them, can you force push again to trigger the CI?
thanks!

**Comment by SomeoneToIgnore** [comment]
Done. I can also reopen the PR, if that won't help.

**Comment by SomeoneToIgnore** [comment]
Let's see if that helps: https://github.com/rust-db/refinery/pull/98

**Comment by SomeoneToIgnore** [comment]
Another attempt, with a fresh new branch: https://github.com/rust-db/refinery/pull/99

**Pull request closed without merging**
