### PR TITLE
Bump mysql version

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**

### CODE REVIEW

**Comment by jxs** [comment]
don't worry i am going to merge this, and see if it runs the tests after merged

**Comment by jxs** [comment]
tests are failing, they are still using the previous api: https://app.circleci.com/pipelines/github/rust-db/refinery/365/workflows/c569ed7a-8388-4868-a104-facd42af9c66/jobs/5501/steps

i will try to fix them later

**Comment by SomeoneToIgnore** [comment]
Thanks a lot!

**Comment by jxs** [comment]
I have published `refinery_core 0.3.1`, refinery should use it automatically if you run `cargo update`
thanks!

**Pull request merged**
